apiVersion: v1
kind: Service
metadata:
  namespace: %NAMESPACE%
  name: %NAMESPACE%-pgpool
  labels:
    name: database-balancer
    node: pgpool
    system: %NAMESPACE%
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    name: database-balancer
    node: pgpool
    system: %NAMESPACE%