apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-data-%NAMESPACE%-db-node-0
  labels:
    system: %NAMESPACE%-db
    node: node-0
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 100Gi
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /mnt/db-data-%NAMESPACE%-db-node-0
