apiVersion: v1
kind: Service
metadata:
  namespace: %NAMESPACE%
  name: %NAMESPACE%-db
  labels:
    name: database
    system: %NAMESPACE%
spec:
  clusterIP: None
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    name: database
    system: %NAMESPACE%
    